
### create user
POST  http://localhost:5000/api/auth/register 
Content-Type: application/json

{
    "username": "test1",
    "password": "12345"
}


### login
POST http://localhost:5000/api/auth/login 
Content-Type: application/json

{
    "username": "test1",
    "password": "1234"
}

### Create Post
POST http://localhost:5000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNmNWFiMzQyNGJjZDFmMDBlMTViYTIiLCJpYXQiOjE2MzE1NDE5NDB9.0jECnWJFIFdtJGa5ybIVzIIAKmUnOugOxQsYjMKwVc4

{
    "title": "expressjs1",
    "description": "nodejs",
    "url": "https://expressjs.org",
    "status": "TO LEARN"
}

### get post 
GET http://localhost:5000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNmNWFiMzQyNGJjZDFmMDBlMTViYTIiLCJpYXQiOjE2MzE1NDE5NDB9.0jECnWJFIFdtJGa5ybIVzIIAKmUnOugOxQsYjMKwVc4



### Update Post
PUT http://localhost:5000/api/post/613d8a119a506b46c9fe6218
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNmNWFiMzQyNGJjZDFmMDBlMTViYTIiLCJpYXQiOjE2MzE1NDE5NDB9.0jECnWJFIFdtJGa5ybIVzIIAKmUnOugOxQsYjMKwVc4

{
    "title": "test",
    "status": "TO LEARN"
}


### delete Post
DELETE  http://localhost:5000/api/post/613d8a119a506b46c9fe6218
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNmNWFiMzQyNGJjZDFmMDBlMTViYTIiLCJpYXQiOjE2MzE1NDE5NDB9.0jECnWJFIFdtJGa5ybIVzIIAKmUnOugOxQsYjMKwVc4



### 
GET http://localhost:5000/api/auth/